---

- hosts: localhost

  vars:
     source: /var/www/html/nextcloud/data
     target: "{{ mytarget | default('/var/nextcloud/data') }}"


  tasks:

     - name: Create target parent directory if needed
       file:
          path: '{{ target | dirname }}'
          state: directory

     - name: Move Nextcloud data directory
       command: mv -v '{{source}}' '{{target}}'

     - name: Remove symlink
       file:
          path: '{{source}}'
          state: absent

     - name: Create link to data directory
       file:
          src: '{{target}}'
          dest: '{{source}}'
          state: link

     - name: Reconfigure Apache
       lineinfile:
          dest: /etc/apache2/sites-enabled/000-default.conf
          state: present
          line: "Options -FollowSymlinks"

     - name: Restart Apache
       service:
          name: apache2
          state: restarted
          enabled: yes

